const listCategory =[
    {id:1,name:"LEGO General", children:[
            {id:11,name:"Angry Birds"},
            {id:12,name:"Architecture"},
            {id:13,name:"BIONICLE"},
            {id:14,name:"BOOST"}
        ]},
    {id:2,name:"LEGO Angry Birds"},
    {id:3,name:"LEGO Architecture"},
    {id:4,name:"LEGO BIONICLE"},
    {id:5,name:"LEGO BOOST"},
    {id:6,name:"LEGO Pirates of the Caribbean"},
    {id:7,name:"LEGO Brick Based Promotions"},
    {id:8,name:"LEGO BrickHeadz"},
    {id:9,name:"LEGO Build A Mini"},
    {id:10,name:"LEGO Castle"},
    {id:11,name:"LEGO Chima"},
    {id:12,name:"LEGO City"},
    {id:13,name:"LEGO Classic"},
    {id:14,name:"LEGO Creator"},
    {id:15,name:"LEGO Creator Expert"},
    {id:16,name:"LEGO DC Comics Super Heroes"},
    {id:17,name:"LEGO DC Super Hero Girls"},
    {id:18,name:"LEGO DIMENSIONS"},
    {id:19,name:"LEGO Disney Princess"},
    {id:20,name:"LEGO Disney"},
    {id:21,name:"LEGO DUPLO"},
    {id:22,name:"LEGO Elves"},
    {id:23,name:"LEGO Forma"},
    {id:24,name:"LEGO Friends"},
    {id:25,name:"LEGO Functions"},
    {id:26,name:"LEGO Galaxy Squad"},
    {id:27,name:"LEGO Games"},
    {id:28,name:"LEGO Ghostbusters"},
    {id:29,name:"LEGO Gift With Purchase"},
    {id:30,name:"LEGO Harry Potter"},
    {id:31,name:"LEGO Hero Factory"},
    {id:32,name:"LEGO House"},
    {id:33,name:"LEGO Ideas"}

]
export default listCategory